/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module testtbl_8 (
    input [7:0] step,
    output reg [37:0] vec
  );
  
  
  
  localparam ADD = 6'h00;
  
  localparam SUB = 6'h01;
  
  localparam MUL = 6'h02;
  
  localparam AND = 6'h18;
  
  localparam OR = 6'h1e;
  
  localparam XOR = 6'h16;
  
  localparam A_ = 6'h1a;
  
  localparam B_ = 6'h1c;
  
  localparam BCA = 6'h12;
  
  localparam ACB = 6'h14;
  
  localparam SHL = 6'h20;
  
  localparam SHR = 6'h21;
  
  localparam SRA = 6'h23;
  
  localparam ROL = 6'h24;
  
  localparam ROR = 6'h25;
  
  localparam RVA = 6'h27;
  
  localparam CMPEQ = 6'h33;
  
  localparam CMPLT = 6'h35;
  
  localparam CMPLE = 6'h37;
  
  localparam START = 6'h00;
  
  localparam END = 6'h3f;
  
  localparam TESTSTEP = 494'h3f00000000cc400440067f000000096ffc00012000100010600404040420fff00020800400404180010002040140004000fff00020000080028000000000;
  
  always @* begin
    vec = TESTSTEP[(step)*38+37-:38];
  end
endmodule
