/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     DIV = 16
*/
module disp7seg_15 (
    input clk,
    input rst,
    input [19:0] digits,
    output reg [6:0] seg,
    output reg [3:0] sel
  );
  
  localparam DIV = 5'h10;
  
  
  reg [4:0] segcode;
  
  wire [2-1:0] M_ctr_value;
  counter_18 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  
  wire [4-1:0] M_digit_dec_out;
  reg [2-1:0] M_digit_dec_in;
  decoder_19 digit_dec (
    .in(M_digit_dec_in),
    .out(M_digit_dec_out)
  );
  
  always @* begin
    segcode = digits[(M_ctr_value)*5+4-:5];
    
    case (segcode)
      1'h0: begin
        seg = 7'h3f;
      end
      1'h1: begin
        seg = 7'h06;
      end
      2'h2: begin
        seg = 7'h5b;
      end
      2'h3: begin
        seg = 7'h4f;
      end
      3'h4: begin
        seg = 7'h66;
      end
      3'h5: begin
        seg = 7'h6d;
      end
      3'h6: begin
        seg = 7'h7d;
      end
      3'h7: begin
        seg = 7'h07;
      end
      4'h8: begin
        seg = 7'h7f;
      end
      4'h9: begin
        seg = 7'h67;
      end
      4'ha: begin
        seg = 7'h77;
      end
      4'hb: begin
        seg = 7'h7c;
      end
      4'hc: begin
        seg = 7'h39;
      end
      4'hd: begin
        seg = 7'h5e;
      end
      4'he: begin
        seg = 7'h79;
      end
      4'hf: begin
        seg = 7'h71;
      end
      5'h10: begin
        seg = 7'h00;
      end
      5'h11: begin
        seg = 7'h5c;
      end
      5'h12: begin
        seg = 7'h58;
      end
      5'h13: begin
        seg = 7'h1c;
      end
      5'h14: begin
        seg = 7'h54;
      end
      5'h15: begin
        seg = 7'h50;
      end
      5'h16: begin
        seg = 7'h67;
      end
      5'h17: begin
        seg = 7'h40;
      end
      5'h18: begin
        seg = 7'h73;
      end
      5'h19: begin
        seg = 7'h76;
      end
      5'h1a: begin
        seg = 7'h38;
      end
      5'h1b: begin
        seg = 7'h74;
      end
      5'h1c: begin
        seg = 7'h6e;
      end
      5'h1d: begin
        seg = 7'h78;
      end
      5'h1e: begin
        seg = 7'h5f;
      end
      5'h1f: begin
        seg = 7'h08;
      end
      default: begin
        seg = 7'h00;
      end
    endcase
    M_digit_dec_in = M_ctr_value;
    sel = M_digit_dec_out;
  end
endmodule
